language: node_js
node_js:
  - "0.11"
  - "0.10"
before_script: 
 - npm install -g codeclimate-test-reporter
 - npm install -g istanbul
script: istanbul cover -v test/run.js 
after_script:
 - codeclimate < coverage/lcov.info
addons:
 code_climate:
  repo_token: 6a36a96aff4a5d9065fe683523decfc6c70a8d6b1a693d703ee009d73e134c25
matrix:
 allow_failures:
  - node_js: "0.11"