sudo: false
language: node_js
node_js:
  - "9"
  - "8"
  - "7"
  - "6"
  - "5"
  - "4"
  - "3"
  - "2"
  - "1"
  - "0.12"
  - "0.11"
  - "0.10"
before_script: 
 - npm install -g istanbul
 - npm install -g codeclimate-test-reporter
script: istanbul cover -v test/run.js 
after_script:
 - codeclimate-test-reporter < coverage/lcov.info
env: 
 - CODECLIMATE_REPO_TOKEN=fdfc4a3bccf85b448bcc19d585095449e22f9e19d54b29f9bde054b6f2bbd7c73
 